### ISSUE TITLE
SimplePendulum vs. NonlinearPendulum

### ISSUE THREAD

**Issue by tbeu** [xogeny/FirstBookExamples#1]
Why is Chapter2.SimplePendulum a runnable example and Chapter2.NonlinearPendulum is not? Both models are printed without the runnable code extensions in the book and are used by Chapter2.ComparePendulums.

@dietmarw FYI

**Comment by xogeny** [comment]
I have no idea.  I wrote this book 15 years. ago. :-)

**Comment by dietmarw** [comment]
So no reason really then.
